### ISSUE TITLE
No "flat_color_icons.dart"

### ISSUE THREAD

**Issue by kevinxxq** [andronasef/iconify_flutter#1]
Hi There,
It is so great to combine so many icons. Thank you.

Would you please check whether you have missed FlatColorIcons.dart.
Thank you.

**Comment by andronasef** [comment]
as i see you skipped reading readme carefully 
there is a step to search for the icon that you need in [iconify flutter explorer](https://andronasef.github.io/iconify_flutter)

for example 
open site then find colored icon set like emojione then click on icon  that you want then you will see what you need to import to use the icon 

that it i hope i understand your problem and solved it

**Comment by kevinxxq** [comment]
Yes, I do really explore the websites:
I searched "flow" and chose the bellow icon:
![image](https://user-images.githubusercontent.com/55800697/158917371-e512354c-e854-4ea7-9eb9-782576225d1c.png)

 and then got something like this:
```
import 'package:iconify_flutter/iconify_flutter.dart';
import 'package:iconify_flutter/icons/flat_color_icons.dart';

Iconify(FlatColorIcons.workflow) // widget
```

When I checked the "flat_color_icons.dart", there is no such file.

Thank you.

**Comment by andronasef** [comment]
@kevinxxq 
first thank you for telling me about this issue
second please try again. i just fix it 
and please tell me if you find any issue again

but waiting for github actions to deploy the website 

thank you

**Comment by andronasef** [comment]
@kevinxxq can you try it now pls

**Comment by kevinxxq** [comment]
> @kevinxxq first thank you for telling me about this issue second please try again. i just fix it and please tell me if you find any issue again
> 
> but waiting for github actions to deploy the website
> 
> thank you

Would you please check the github actions done or not?

**Comment by andronasef** [comment]
I have fixed it

**Comment by andronasef** [comment]
> > @kevinxxq first thank you for telling me about this issue second please try again. i just fix it and please tell me if you find any issue again
> > but waiting for github actions to deploy the website
> > thank you
> 
> Would you please check the github actions done or not?

Please check it again. It's ready.

**Comment by kevinxxq** [comment]
Hi Andrew,
Looks like the version is not updated as expected.

Added/updated 'iconify_flutter' (version 0.0.2) and sorted file.
![image](https://user-images.githubusercontent.com/55800697/159138267-cff6feda-c32f-4d8a-8713-353b1429e530.png)

![image](https://user-images.githubusercontent.com/55800697/159138345-09125637-d2e8-4262-b5b6-60255bfc680c.png)

I thought it is from Github Actions but now I guess there is something wrong since you have closed it.

Would you please check it again? 
Thank you.

**Comment by andronasef** [comment]
![Web capture_20-3-2022_036_andronasef ninja](https://user-images.githubusercontent.com/41882346/159139938-546a5433-49c4-4a78-93ea-81a450e369b2.jpeg)

I am sorry but you miss understand me.
Did you bro checked the [iconfiy flutter explorer](https://andronasef.ninja/iconify_flutter)?

Thank You ❤️
Without you i would never find these bugs

**Comment by andronasef** [comment]
Check https://andronasef.ninja/iconify_flutter/collection/flat-color-icons please

**Comment by kevinxxq** [comment]
Hi Andrew,
I am very sorry. Now I checked it and works very good.

Thank you.
