### ISSUE TITLE
100 stars challenge done

### ISSUE THREAD

**Issue by gochev** [andronasef/iconify_flutter#17]
Update the readme :) 

![IMG_2168](https://github.com/user-attachments/assets/425f0a52-1855-42d2-9762-da8c73c40f71)

before today:

![IMG_2166](https://github.com/user-attachments/assets/e3211071-49c0-41ea-acda-00c8854b925f)

after my star the dream came true :)

![IMG_2167](https://github.com/user-attachments/assets/ac9e6931-bd8f-45aa-a6e6-ba7ae7a8ae94)

**Comment by andronasef** [comment]
شكرا يا كبير ❤
THX that You Care 🤩❤
