### ISSUE TITLE
Need change "-" to "_"

### ISSUE THREAD

**Issue by kevinxxq** [andronasef/iconify_flutter#2]
Hi There,
Would you please change the "-" to "_" in the website:

```
import 'package:iconify_flutter/iconify_flutter.dart';
import 'package:iconify_flutter/icons/carbon.dart';

Iconify(Carbon.chart-multi-line) // widget
```

The correct one should be:

`Iconify(Carbon.chart_multi_line) // widget`

Thank you.

**Comment by andronasef** [comment]
just solved 

but waiting for github actions to deploy the website

**Comment by andronasef** [comment]
@kevinxxq can you try it now pls

**Comment by kevinxxq** [comment]
Thank you. Some of them still need be changed:
Iconify(Carbon.settings-check) // widget

Thank you.

**Comment by andronasef** [comment]
> Thank you. Some of them still need be changed: Iconify(Carbon.settings-check) // widget
> 
> Thank you.

![Uploading Screenshot_2022-03-18-21-52-58-68.jpg…]()

**Comment by andronasef** [comment]
> Thank you. Some of them still need be changed: Iconify(Carbon.settings-check) // widget
> 
> Thank you.

![Uploading Screenshot_2022-03-18-21-52-58-68.jpg…]()

**Comment by andronasef** [comment]
Pleas

> Thank you. Some of them still need be changed: Iconify(Carbon.settings-check) // widget
> 
> Thank you.

Please try again

**Comment by kevinxxq** [comment]
Hi Andrew,
I am very sorry. Now I checked it and works very good.

Thank you.
