### ISSUE TITLE
Importing fluent icons does not work

### ISSUE THREAD

**Issue by Bakri-Alkhateeb** [andronasef/iconify_flutter#8]
Hello, 

I have updated the package to version 0.0.5 and suddenly the import "import 'package:iconify_flutter/icons/fluent.dart';" is not working anymore. Then I looked at the files and the fluent.dart is deleted.

is there something wrong with the fluent.dart?

**Comment by andronasef** [comment]
I am feel sorry 😐

But I had to remove some icon sets like fluent because of pub.dev limits the package size to be under 100mb

Sorry again but to solve this issue you have to rollback to version 0.0.5 

Thanks 🙏

**Comment by Luducrous** [comment]
I was very happy to find this comment, since I have the same problem as @Bakri-Alkhateeb.

However, I come from package version 0.0.4 and upgraded to 0.0.5 and the package:iconify_flutter/icons/fluent.dart became non-existent.
Although I go back to version 0.0.4 it is still no longer available.

Any help?

**Comment by Luducrous** [comment]
Sad that the restriction for the package is 100 MB. I see the fluent.dart file is rather big with 9.2 MB compared to the others.
I was able to find a cached version of the package installed in my Developer folder.
Extracted the fluent.dart from there and put it inside the lib of my project to import it from there.

**Comment by Bakri-Alkhateeb** [comment]
@andronasef Thank you for explaining.

@Luducrous Yes, that is the same thing that I did. I added the fluent.dart manually to version 0.0.5

**Comment by andronasef** [comment]
@Bakri-Alkhateeb  @Luducrous 
Thanks for understanding 😊

And I am happy that you could fix your issue

**Comment by Dampfwalze** [comment]
Maybe you can create a sub package for these large icon sets and depend on it from the main package!

Then in `'package:iconify_flutter/icons/fluent.dart'` you could just export them like this:

```dart
export 'package:iconify_flutter_fluent/icons/fluent.dart'
// package:iconify_flutter_fluent would be the sub package for fluent
```

**Comment by andronasef** [comment]
> Maybe you can create a sub package for these large icon sets and depend on it from the main package!
> 
> Then in `'package:iconify_flutter/icons/fluent.dart'` you could just export them like this:
> 
> ```dart
> export 'package:iconify_flutter_fluent/icons/fluent.dart'
> // package:iconify_flutter_fluent would be the sub package for fluent
> ```

I have thought about it but it will take me to make more than 3 packages 

Sorry 😐 but it will be hard

**Comment by AbderraoufKhodja** [comment]
This should appear in the change log.
