### ISSUE TITLE
Null safety support for dependent package 'colorful_iconify_flutter'

### ISSUE THREAD

**Issue by imhafeez** [andronasef/iconify_flutter#9]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:colorful_iconify_flutter

**Comment by definitelyme** [comment]
Any fix for this issue?

**Comment by imhafeez** [comment]
@definitelyme yes. you can use my fork
```
iconify_flutter:
    git: https://github.com/imhafeez/iconify_flutter.git
```

I will send pull request as well to merge

**Comment by AbderraoufKhodja** [comment]
Not fixed yet?

**Comment by imhafeez** [comment]
@AbderraoufKhodja sent a pull request. but its not merged yet.

**Comment by NonymousMorlock** [comment]
bruh, it's been over 20 days

**Comment by andronasef** [comment]
> bruh, it's been over 20 days

sorry but it was hobby project that I didn't think that so much people will use (and also i had a bit weak laptop to continue development + I lost passion)

so I am sorry for late update 😥 @imhafeez @NonymousMorlock @AbderraoufKhodja  @definitelyme

**Comment by NonymousMorlock** [comment]
Look who it is, welcome back @andronasef

**Comment by andronasef** [comment]
> Look who it is, welcome back @andronasef

@NonymousMorlock thanks ❤🤩
